version: "3"
services:

        # Data stores (SQL)
        mssql:
                image: microsoft/mssql-server-linux:latest
                container_name: mssql
                ports:
                - "1433:1433"
                environment:
                - ACCEPT_EULA=Y
                - MSSQL_PID=Express
                - SA_PASSWORD=Password123!

        postgres:
                image: postgres:latest
                container_name: postgres
                ports:
                - "5432:5432"
                environment:
                - POSTGRES_PASSWORD=Password123!

        # Data stores (NoSQL)
        redis:
                image: redis:latest
                container_name: redis
                ports:
                - "6379:6379"      

        elasticsearch:
                image: elasticsearch:7.9.0  # doesn't have a "latest"
                container_name: elasticsearch
                environment:
                - discovery.type=single-node
                ports:
                - "9200:9200"
                - "9300:9300"

        mongo:
                image: mongo:latest
                container_name: mongo
                environment:
                - MONGO_INITDB_ROOT_USERNAME=root
                - MONGO_INITDB_ROOT_PASSWORD=Password123!                
                ports:
                - "27017:27017"  # db
                - "28017:28017"  # web


        # Middleware
        # TODO

        # Dev/build containers
        rust:
                image: rust:latest
                container_name: rust
                volumes:
                - ./src:/usr/src
                environment:
                - USER    # cargo needs that one
                stdin_open: true 
                tty: true
                working_dir: /usr/src


        dotnet:
                image: mcr.microsoft.com/dotnet/core/sdk:latest
                container_name: dotnet
                volumes:
                - ./src:/usr/src
                environment:
                - USER
                stdin_open: true 
                tty: true
                working_dir: /usr/src
