version: "3"
services:
        mssql:
                image: microsoft/mssql-server-linux:latest
                container_name: mssql
                ports:
                        - "1433:1433"
                environment:
                        - ACCEPT_EULA=Y
                        - MSSQL_PID=Express
                        - SA_PASSWORD=Password123!

        redis:
                image: redis:latest
                container_name: redis
                ports:
                        - "6379:6379"                        




        dotnet:
                image: mcr.microsoft.com/dotnet/core/sdk:latest
                container_name: dotnet
                volumes:
                - ./src:/usr/src
                environment:
                - USER
                stdin_open: true 
                tty: true
                working_dir: /usr/src
